from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import pandas as pd
import os
from datetime import datetime
import os.path

# Import the prediction function.
try:
    from predict import predict_volume_and_save_images 
except ImportError:
    print("ERROR: Could not import 'predict.py'. Using security mock function.")
    def predict_volume_and_save_images(uploaded_top_path, uploaded_side_path, output_dir, cell_name):
        return 0.0, "Prediction error", "Prediction error"


app = Flask(__name__)
# CORS Configuration: allows communication with the React frontend
CORS(app, resources={r"/api/*": {"origins": "http://localhost:3000"}})

# --- 1. PATH CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) 
UPLOAD_FOLDER = os.path.join(BASE_DIR, 'uploaded_images')
PREDICTED_FOLDER = os.path.join(BASE_DIR, 'predicted_images')
# The log file is saved in the parent project folder
LOG_FILE = os.path.join(os.path.dirname(BASE_DIR), 'data_log.csv') 

# Ensure folders exist
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(PREDICTED_FOLDER, exist_ok=True)


# --- 2. UTILITY FUNCTIONS ---

def load_data_log():
    """Loads the log file (CSV) or creates an empty DataFrame."""
    if os.path.exists(LOG_FILE) and os.path.getsize(LOG_FILE) > 0:
        try:
            return pd.read_csv(LOG_FILE)
        except pd.errors.EmptyDataError:
            print("Warning: data_log.csv is empty.")
            pass
    
    # If the file does not exist, is empty, or reading fails, create the empty DataFrame
    return pd.DataFrame(columns=['Cell Name', 'Measurement ID', 'Upload Date', 'Estimated Volume (mL)', 'Image Location (Top)', 'Image Location (Side)'])

def get_image_urls_from_path(row):
    """
    Converts the local file paths saved in the CSV to URLs accessible by the frontend.
    It reconstructs the URL based on the date/cell/filename convention.
    """
    try:
        # Extract the date string from the 'Upload Date' column
        date_str = datetime.strptime(row['Upload Date'].split(' ')[0], "%Y-%m-%d").strftime("%Y-%m-%d")
        
        # Predicted filenames generated by predict.py
        top_filename = f"{row['Cell Name']}_TOP_predicted.jpg"
        side_filename = f"{row['Cell Name']}_SIDE_predicted.jpg"

        # The relative path is: Date/Cell_Name/File_Name
        base_url_path = os.path.join(date_str, row['Cell Name'])

        return {
            'predicted_image_top_url': f"http://localhost:5000/api/predicted_images/{os.path.join(base_url_path, top_filename)}",
            'predicted_image_side_url': f"http://localhost:5000/api/predicted_images/{os.path.join(base_url_path, side_filename)}",
        }
    except Exception as e:
        print(f"Error reconstructing URLs for row {row['Measurement ID']}: {e}")
        return {
            'predicted_image_top_url': None,
            'predicted_image_side_url': None,
        }


# --- 3. DATA READ ENDPOINTS ---

@app.route('/api/estimations', methods=['GET'])
def list_estimations():
    """Lists all performed estimations."""
    df = load_data_log()
    if df.empty:
        return jsonify({"message": "No estimations recorded."}), 404

    # Select only the columns we want to expose
    df_output = df[['Cell Name', 'Measurement ID', 'Upload Date', 'Estimated Volume (mL)']]
    
    # Add image URLs
    df_output[['predicted_image_top_url', 'predicted_image_side_url']] = df.apply(get_image_urls_from_path, axis=1, result_type='expand')

    # Convert DataFrame to JSON, sorted by upload date (most recent first)
    results = df_output.sort_values(by='Upload Date', ascending=False).to_dict(orient='records')
    
    return jsonify(results), 200

@app.route('/api/estimations/summary', methods=['GET'])
def get_estimations_summary():
    """
    Devuelve un resumen de las estimaciones por célula, incluyendo:
    - Última estimación
    - Cantidad de veces estimada
    - Valor de la última estimación
    - Fecha de la última estimación
    """
    df = load_data_log()
    if df.empty:
        return jsonify([]), 200 # Devolvemos un array vacío si no hay datos

    # Aseguramos que la columna de fecha sea un objeto datetime para la comparación
    df['Upload Date'] = pd.to_datetime(df['Upload Date'])
    
    # 1. Encontrar la última estimación por célula
    # Ordenamos por fecha descendente y tomamos el primer registro de cada grupo ('Cell Name')
    last_estimation = df.sort_values(by='Upload Date', ascending=False).drop_duplicates(subset=['Cell Name'], keep='first')

    # 2. Calcular la cantidad total de mediciones por célula
    count_estimations = df.groupby('Cell Name')['Measurement ID'].count().reset_index()
    count_estimations = count_estimations.rename(columns={'Measurement ID': 'Estimated Count'})

    # 3. Combinar los resultados
    # Seleccionamos las columnas clave de la última medición
    summary = last_estimation[['Cell Name', 'Estimated Volume (mL)', 'Upload Date', 'Measurement ID']].copy()
    
    # Renombrar columnas para claridad en la respuesta JSON
    summary.rename(columns={
        'Estimated Volume (mL)': 'Last Estimated Volume (mL)',
        'Upload Date': 'Last Estimation Date',
        'Measurement ID': 'Last Measurement ID'
    }, inplace=True)

    # Fusionar con el conteo de estimaciones
    summary = pd.merge(summary, count_estimations, on='Cell Name', how='left')

    # 4. Añadir las URLs de imagen para la última medición
    # Usamos la función existente para obtener las URLs
    summary[['predicted_image_top_url', 'predicted_image_side_url']] = summary.apply(get_image_urls_from_path, axis=1, result_type='expand')

    # 5. Formatear la fecha para la respuesta JSON
    summary['Last Estimation Date'] = summary['Last Estimation Date'].dt.strftime("%Y-%m-%d %H:%M:%S")

    # Convertir el DataFrame a una lista de diccionarios (JSON)
    results = summary.to_dict(orient='records')
    
    return jsonify(results), 200

@app.route('/api/estimations/latest', methods=['GET'])
def list_latest_estimations():
    """Lists the last 10 performed estimations."""
    df = load_data_log()
    if df.empty:
        return jsonify({"message": "No estimations recorded."}), 404

    # Sort by upload date (most recent first) and select the first 10
    df_latest = df.sort_values(by='Upload Date', ascending=False).head(10)
    
    df_output = df_latest[['Cell Name', 'Measurement ID', 'Upload Date', 'Estimated Volume (mL)']]
    
    # Add image URLs
    df_output[['predicted_image_top_url', 'predicted_image_side_url']] = df_latest.apply(get_image_urls_from_path, axis=1, result_type='expand')

    results = df_output.to_dict(orient='records')
    
    return jsonify(results), 200

@app.route('/api/estimations/<string:cell_name>', methods=['GET'])
def get_cell_history(cell_name):
    """Gets the estimation history for a specific cell."""
    df = load_data_log()
    if df.empty:
        return jsonify({"message": "No estimations recorded."}), 404

    # Filter by cell name
    cell_data = df[df['Cell Name'] == cell_name]
    
    if cell_data.empty:
        return jsonify({"message": f"No estimations found for cell: {cell_name}"}), 404

    # Select columns and sort by date (oldest first for history timeline)
    cell_data = cell_data.sort_values(by='Upload Date', ascending=True)
    
    df_output = cell_data[['Cell Name', 'Measurement ID', 'Upload Date', 'Estimated Volume (mL)']]
    
    # Add image URLs
    df_output[['predicted_image_top_url', 'predicted_image_side_url']] = cell_data.apply(get_image_urls_from_path, axis=1, result_type='expand')

    results = df_output.to_dict(orient='records')

    return jsonify(results), 200


# --- 4. PROCESSING ENDPOINT ---

@app.route('/api/predicted_images/<path:filename>')
def serve_predicted_image(filename):
    """Endpoint to serve static images from the 'predicted_images' folder."""
    return send_from_directory(PREDICTED_FOLDER, filename)


@app.route('/api/analyze', methods=['POST'])
def analyze_cell():
    """Main endpoint to receive images, process, and log data."""
    
    if 'cell_name' not in request.form or 'image_top' not in request.files or 'image_side' not in request.files:
        return jsonify({"error": "Missing required data (cell_name, image_top, or image_side)."}), 400

    cell_name = request.form['cell_name']
    file_top = request.files['image_top']
    file_side = request.files['image_side']
    
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%Y%m%d%H%M%S")
    measurement_id = f"{cell_name}-{timestamp}"
    
    # Save Paths (Structure: Date/Cell)
    day_upload_dir = os.path.join(UPLOAD_FOLDER, date_str)
    cell_upload_dir = os.path.join(day_upload_dir, cell_name) 
    os.makedirs(cell_upload_dir, exist_ok=True) 

    day_predicted_dir = os.path.join(PREDICTED_FOLDER, date_str)
    cell_predicted_dir = os.path.join(day_predicted_dir, cell_name)
    os.makedirs(cell_predicted_dir, exist_ok=True)

    filename_top = f"{cell_name}_top_{timestamp}{os.path.splitext(file_top.filename)[1]}"
    filename_side = f"{cell_name}_side_{timestamp}{os.path.splitext(file_side.filename)[1]}"
    
    path_top = os.path.join(cell_upload_dir, filename_top)
    path_side = os.path.join(cell_upload_dir, filename_side)
    
    file_top.save(path_top)
    file_side.save(path_side)

    # Execute Prediction
    try:
        estimated_volume, predicted_top_path, predicted_side_path = predict_volume_and_save_images(
            path_top, 
            path_side, 
            cell_predicted_dir, 
            cell_name
        )
    except Exception as e:
        print(f"Fatal error during prediction for {cell_name}: {e}")
        return jsonify({"error": f"Internal prediction model error: {str(e)}"}), 500

    # Log to CSV
    df = load_data_log()
    new_row = {
        'Cell Name': cell_name,
        'Measurement ID': measurement_id,
        'Upload Date': now.strftime("%Y-%m-%d %H:%M:%S"),
        'Estimated Volume (mL)': estimated_volume,
        'Image Location (Top)': path_top, 
        'Image Location (Side)': path_side, 
    }
    
    df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    df.to_csv(LOG_FILE, index=False)

    # Return response with URLs
    top_url_path = os.path.join(date_str, cell_name, os.path.basename(predicted_top_path))
    side_url_path = os.path.join(date_str, cell_name, os.path.basename(predicted_side_path))

    return jsonify({
        "status": "success",
        "measurement_id": measurement_id,
        "cell_name": cell_name,
        "estimated_volume": estimated_volume,
        "predicted_image_top_url": f"http://localhost:5000/api/predicted_images/{top_url_path}", 
        "predicted_image_side_url": f"http://localhost:5000/api/predicted_images/{side_url_path}",
    }), 200

# --- 5. SERVER EXECUTION ---

if __name__ == '__main__':
    print(f"Data log saved to: {LOG_FILE}")
    print("Starting Flask server at http://localhost:5000...")
    app.run(debug=True, port=5000)